### PR TITLE
Flutter 2.0 + null safety + androidX

### PR DESCRIPTION
**Pull request by andzejsw**
Plugin now supports Flutter 2.0. Also includes null safety migration and migration to AndroidX packages

### CODE REVIEW

**Comment by andzejsw** [comment]
@wrbl606, @SPodjasek please take a look.

**Review by SPodjasek — APPROVED** [review]

**Comment by SPodjasek** [comment]
Closes #19

**Comment by andzejsw** [comment]
> Closes #19

Wow. That was fast. Tnx. Also if you have time, please publish changes to pub.dev, if you have access.

**Comment by SPodjasek** [comment]
@andzejsw Published as new major version

**Pull request merged**
